spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orai?serverTimezone=UTC&characterEncoding=UTF-8
    password: phj@3473
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /api
